# PlatformIO pre-build script: embeds the web UI from data/ into PROGMEM.
# Adapted from CYD-RGB-LED-Matrix-HUB75-Retro-Clock (same pattern across CYD projects).
#
# data/ stays the editable source. Every build regenerates src/web_assets.h
# (gitignored), so the firmware image alone carries the web UI - no LittleFS
# image or `uploadfs` step, and the web installer's four parts are enough.
# The header is only rewritten when its content changes, so an unchanged UI
# doesn't force a recompile.

Import("env")  # noqa: F821 - provided by PlatformIO/SCons

import os

# (file in data/, C symbol prefix)
WEB_FILES = [
    ("index.html", "INDEX_HTML"),
    ("clock.js", "CLOCK_JS"),
    ("style.css", "STYLE_CSS"),
    ("pong-logo.png", "PONG_LOGO_PNG"),
]

project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
data_dir = os.path.join(project_dir, "data")
out_path = os.path.join(project_dir, "src", "web_assets.h")

lines = [
    "// Generated by tools/embed_web.py from data/ - do not edit, edit data/ instead.",
    "#pragma once",
    "#include <Arduino.h>",
    "",
]
for name, sym in WEB_FILES:
    with open(os.path.join(data_dir, name), "rb") as f:
        data = f.read()
    lines.append("// data/%s" % name)
    lines.append("static const uint8_t %s[] PROGMEM = {" % sym)
    for i in range(0, len(data), 20):
        lines.append("  " + ",".join("0x%02x" % b for b in data[i:i + 20]) + ",")
    lines.append("};")
    lines.append("static const size_t %s_LEN = %d;" % (sym, len(data)))
    lines.append("")
content = "\n".join(lines)

old = None
if os.path.exists(out_path):
    with open(out_path) as f:
        old = f.read()
if content != old:
    with open(out_path, "w") as f:
        f.write(content)
    print("embed_web: wrote src/web_assets.h")
